name: barbershop
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # ğŸŒ ĞĞ°Ğ²Ğ¸Ğ³Ğ°Ñ†Ğ¸Ñ
  go_router: ^13.2.0

  # ğŸ“¦ Ğ¡Ğ¾ÑÑ‚Ğ¾ÑĞ½Ğ¸Ğµ
  flutter_riverpod: ^2.4.5

  # ğŸ” Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10

  # ğŸ”” Ğ£Ğ²ĞµĞ´Ğ¾Ğ¼Ğ»ĞµĞ½Ğ¸Ñ
  onesignal_flutter: ^5.0.4

  # ğŸ—“ï¸ Ğ”Ğ°Ñ‚Ñ‹, Ğ²Ñ€ĞµĞ¼Ñ
  intl: ^0.20.2
  table_calendar: ^3.2.0

  # âœ… Ğ’Ğ°Ğ»Ğ¸Ğ´Ğ°Ñ†Ğ¸Ñ, Ñ„Ğ¾Ñ€Ğ¼Ñ‹
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.5

  # ğŸ“± UI Ğ¸ Ğ°Ğ½Ğ¸Ğ¼Ğ°Ñ†Ğ¸Ğ¸
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  animations: ^2.0.8
  shimmer: ^3.0.0

  # ğŸ“¤ Ğ—Ğ°Ğ³Ñ€ÑƒĞ·ĞºĞ° Ğ¸Ğ·Ğ¾Ğ±Ñ€Ğ°Ğ¶ĞµĞ½Ğ¸Ğ¹
  image_picker: ^1.0.7

  # ğŸ’¬ Toast / Snackbar
  fluttertoast: ^8.2.4
  another_flushbar: ^1.12.30

  # ğŸ“¶ ĞŸÑ€Ğ¾Ğ²ĞµÑ€ĞºĞ° Ğ¿Ğ¾Ğ´ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ñ
  connectivity_plus: ^6.0.3

  # ğŸ’¾ Ğ›Ğ¾ĞºĞ°Ğ»ÑŒĞ½Ğ¾Ğµ Ñ…Ñ€Ğ°Ğ½Ğ¸Ğ»Ğ¸Ñ‰Ğµ
  shared_preferences: ^2.2.2

  # ğŸ§ª Dev
  flutter_launcher_icons: ^0.13.1
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
  assets:
    - assets/images/
